### PR TITLE
fix: use private org for location when set

### LINKED ISSUE #137: The create/edit mirror dialog shows the wrong organization in "Mirror location"
### Describe the bug

The create/edit mirror dialog has a preview of the mirror's location in `owner/repo` format. However, the `owner` currently shown is the owner of the **public forks** when it should actually be the org where **private mirrors** live.

### To Reproduce

1. Create a new mirror
2. Note the dialog "Mirror location" shows an `owner/repo` , but the `owner` is of the current/public org.
3. Create the mirror and click the link; the `owner` url will be the private org, so the preview is inaccurate.

### Expected behavior

The "Mirror location" should show the private organization.

### Screenshots

_No response_

### Additional context

Image

### PR DESCRIPTION
**Pull request by sutterj**
# Pull Request

## Proposed Changes

- Closes #137 
  - Add api call to fetch config
  - Use private org for orgLogin when set
  - Show error flash when config fails to load
  - Remove orgName from deleteMirror flash

### Author/Contributor

- [ ] If documentation is needed for this change, has that been included in this pull request
- [X] run `npm run lint` and fix any linting issues that have been introduced
- [X] run `npm run test` and run tests
- [ ] If publishing new data to the public (scorecards, security scan results, code quality results, live dashboards, etc.), please request review from `@jeffrey-luszcz`

### Reviewer

- [X] Label as either `bug`, `documentation`, `enhancement`, `infrastructure`, `maintenance`, or `breaking`

### CODE REVIEW

File: src/server/config/controller.ts [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+    configApiLogger.debug('Fetched config', config)
+
+    return config
+  } catch (error) {
+    configApiLogger.error('Error fetching config', { error })
+
+    throw new TRPCError({
+      code: 'INTERNAL_SERVER_ERROR',
+      message: (error as Error).message,
+    })
```
Comment (ajhenry) [inline src/server/config/controller.ts:28]: Could we add a test for this?

**Review by ajhenry — APPROVED** [review]
lgtm 🚢
